# `sheldon` configuration file
shell = "zsh"

[plugins]
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "romkatv/zsh-syntax-highlighting"
apply = ["defer"]


[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
